### ISSUE TITLE
Feature request: auto install pyenv

### ISSUE THREAD

**Issue by zzzz-qq** [davidparsson/zsh-pyenv-lazy#3]
[mattberther/zsh-pyenv](https://github.com/mattberther/zsh-pyenv) this zsh plugin support auto install pyenv, but its not lazy. It would be convenient to integreate auto install and lazy load pyenv into one plugin. If I create a pull request for auto install for this plugin, could it be accepted?

**Comment by davidparsson** [comment]
Yes, absolutely!

**Comment by davidparsson** [comment]
I'm sorry, but I have changed my mind about this. See motivation: https://github.com/davidparsson/zsh-pyenv-lazy/pull/4#issuecomment-1020985399
