### ISSUE TITLE
Add completions path

### ISSUE THREAD

**Issue by jamnaughty** [davidparsson/zsh-pyenv-lazy#6]
Add completions path

**Comment by davidparsson** [comment]
Hi! Could you please clarify what/how/why?

**Comment by jamnaughty** [comment]
`source '/opt/homebrew/Cellar/pyenv/2.4.5/libexec/../completions/pyenv.zsh'` is set when using `pyenv init -`. Since we might not be using `pyenv init -`, is there a way to source the completions?

**Comment by davidparsson** [comment]
Right, so you want the completions to be loaded before pyenv has been loaded? That's reasonable.

**Comment by davidparsson** [comment]
Ok, I've not researched, but I've given this some thought and I don't think there's a reliable way to find the completions automatically. And configuring that is as complex as sourcing it right away. So I'm leaning towards closing this, although a solution would be sweet.

Do you know of a way to reliably find completions on different platforms?

**Comment by jamnaughty** [comment]
I don't know how. Also, in the recent changes for Pynev, I see the below.

`pyenv --version` shows `pyenv 2.4.4` but `/opt/homebrew/Cellar/pyenv/2.4.5`  is the actual version. `pyenv init -` shows `source '/opt/homebrew/Cellar/pyenv/2.4.5/libexec/../completions/pyenv.zsh'`. 
I am not sure how to do this. I did log this issue of version mismatch with pyenv and they will fix it soon. I just went ahead and modified the `pyenv-lazy.plugin.zsh` and added `source '/opt/homebrew/Cellar/pyenv/2.4.5/libexec/../completions/pyenv.zsh'` to it.

**Comment by davidparsson** [comment]
All right, a workaround like that is as good as anything I can come up with.

Closing (but willing to reopen, if a PR would solve this in a general way).
